added testing
vladshender/BookStore-API pull request #17
Opened 2024-09-20 12:55 UTC by vladshender

![BookController](https://github.com/user-attachments/assets/d2375a5f-a6a6-468a-b618-2c831de6b77a)
![BookRepository](https://github.com/user-attachments/assets/e01c486d-8785-4db5-82b4-87ccc2734af9)
![BookService](https://github.com/user-attachments/assets/4034dada-a312-43d2-a889-db95bc7f4b45)
![CategoryController](https://github.com/user-attachments/assets/45050dd3-acf5-4d95-87c7-6dcbb1f97878)
![CategoryService](https://github.com/user-attachments/assets/97ccaa78-8758-46b3-9440-c9416007467a)

2024-09-29 16:49 UTC, Elena-Bruyako requested changes
see comments, fix everywhere

2024-09-29 16:49 UTC, Elena-Bruyako commented on pom.xml
> +			<groupId>org.testcontainers</groupId>
there is something with tabs, please fix it

2024-09-29 16:49 UTC, Elena-Bruyako commented on src/test/java/com/example/controller/book/BookControllerTest.java
> +        Assertions.assertEquals(3, actual.length);
use static imports

2024-09-29 16:49 UTC, Elena-Bruyako commented on src/test/java/com/example/controller/book/BookControllerTest.java
> +    }
add not valid cases

2024-09-29 16:49 UTC, Elena-Bruyako commented on src/test/java/com/example/controller/category/CategoryControllerTest.java
> +    }
same here

2024-10-04 16:41 UTC, ahoienko approved these changes
Good job!

2024-10-05 06:13 UTC, merged